kind: pipeline
name: Installation

# Configuration
volumes:
  - name: cache
    host: 
      path: /tmp/cache

steps:

# Installation
- name: Adding Submodules
  image: zierhutit/drone-git-submodules
  pull: if-not-exists
  commands:
    - git submodule update --init z_framework 
 
# Deployment
- name: Minify code
  image: thekevjames/minify
  pull: if-not-exists
  commands:
  - minify --recursive --verbose --output /drone/src/ /drone/src/
  trigger:
    branch:
    - master

- name: Delete development files
  image: alpine
  pull: if-not-exists
  commands:
  - rm -rf composer.json composer.lock
  - rm -rf .gitignore uploads
  - rm -rf .drone.yml
  trigger:
    branch:
    - master

- name: Transfer Source
  image: appleboy/drone-scp
  pull: if-not-exists
  settings: 
    host:
      from_secret: scp_host
    user: 
      from_secret: scp_user
    key:
      from_secret: scp_key
    source: 
      - '*'
      - '.*'
    target: '/var/www/tools.repair.wiki/.prod'
    rm: true
    trigger:
      branch:
      - master

- name: Activate Source
  image: appleboy/drone-ssh
  pull: if-not-exists
  settings:
    host:
      from_secret: scp_host
    user: 
      from_secret: scp_user
    key:
      from_secret: scp_key
    script:
      - cd /var/www/tools.repair.wiki/
      - sudo mv prod/ .prod_tmp/
      - sudo mv .prod_tmp/z_config/z_settings.ini .prod/z_config/z_settings.ini 
      - sudo mv .prod_tmp/editor .prod
      - sudo mv .prod/ prod/
      - sudo chown -R www-data prod/
      - sudo rm -rf .prod_tmp/
      - sudo rm -rf .prod/
    trigger:
      branch:
      - master
